server:
  port: 8015
spring:
  application:
    name: spring-boot-jaeger-aop
    id: spring-boot-jaeger-aop
  cloud:
    compatibility-verifier:
      enabled: false
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
    service-name: ${spring.application.name}
    enabled: true
order:
  feign:
    name: order-client
    url: http://localhost:3000